### ISSUE TITLE
Cron: Always process Pending payments, Daily process Scheduled payments

### ISSUE THREAD

**Issue by kenwest** [ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor#23]
I think that we need 2 jobs for this payment processor.

1. 'Always' process Pending payments. This permits donors to get a Contribution receipt in a few minutes (depending how often the CiviCRM cron is run)
2. 'Daily' process Scheduled payments. As the minimum recurrence period is 1 Day, this is adequate.

Thoughts?

**Comment by eileenmcnaughton** [comment]
Pending payments should no longer be relevant? is this closable?

**Comment by eileenmcnaughton** [comment]
per prev comment

**Comment by kenwest** [comment]
Agreed
