### ISSUE TITLE
How do I gain access to to the eWAY settings form?

### ISSUE THREAD

**Issue by kenwest** [ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor#29]
My current version of this extension is 654bb73ed6b00c08c138d7519787cc0f7d5e359a

When I try to upgrade to 705a621e291bd86fdf2b2a2bed113e271fde53fb I do this by replacing the codebase for this extension and hitting Refresh on the Manage Extensions page.

This gives me an "Eway" menu item that points to civicrm/eway/settings but when I click that it takes me to the CiviCRM home page.

I then tried disabling the extension, thinking that I might need to reenable it to gain access to the menu. But when I disable either version of the extension, I get the same fatal error ...

    PHP Fatal error:  require_once(): Failed opening required 'CRM/Core/Payment/Ewayrecurring.php' (include_path='/var/www/citybibleforum/sites/default/files/civicrm/extensions/org.civicrm.sms.clickatell/:/var/www/citybibleforum/sites/default/files/civicrm/extensions/com.webaccessglobal.module.civimobile/code:cbf/php/:.:civicrm:civicrm/packages:.:civicrm:civicrm/packages:.:/usr/share/php:/usr/share/pear') in civicrm/Civi/Payment/System.php on line 52, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP Stack trace:, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   1. {main}() /var/www/citybibleforum/index.php:0, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   2. menu_execute_active_handler() /var/www/citybibleforum/index.php:21, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   3. drupal_deliver_page() /var/www/citybibleforum/includes/menu.inc:532, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   4. drupal_deliver_html_page() /var/www/citybibleforum/includes/common.inc:2605, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   5. drupal_render_page() /var/www/citybibleforum/includes/common.inc:2723, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   6. block_page_build() /var/www/citybibleforum/includes/common.inc:5831, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   7. block_get_blocks_by_region() /var/www/citybibleforum/modules/block/block.module:268, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   8. block_list() /var/www/citybibleforum/modules/block/block.module:318, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP   9. _block_render_blocks() /var/www/citybibleforum/modules/block/block.module:686, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  10. module_invoke() /var/www/citybibleforum/modules/block/block.module:902, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  11. call_user_func_array:{/var/www/citybibleforum/includes/module.inc:866}() /var/www/citybibleforum/includes/module.inc:866, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  12. civicrm_block_view() /var/www/citybibleforum/includes/module.inc:866, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  13. CRM_Core_Block::getContent() civicrm/drupal/civicrm.module:95, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  14. CRM_Core_Block::setTemplateValues() civicrm/CRM/Core/Block.php:629, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  15. CRM_Core_Block::setTemplateShortcutValues() civicrm/CRM/Core/Block.php:297, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  16. CRM_Core_Config::isEnabledBackOfficeCreditCardPayments() civicrm/CRM/Core/Block.php:379, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  17. CRM_Financial_BAO_PaymentProcessor::hasPaymentProcessorSupporting() civicrm/CRM/Core/Config.php:889, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  18. CRM_Financial_BAO_PaymentProcessor::getPaymentProcessors() civicrm/CRM/Financial/BAO/PaymentProcessor.php:400, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  19. CRM_Financial_BAO_PaymentProcessor::getAllPaymentProcessors() civicrm/CRM/Financial/BAO/PaymentProcessor.php:369, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  20. CRM_Core_Payment::singleton() civicrm/CRM/Financial/BAO/PaymentProcessor.php:336, referer: https://x.org/civicrm/admin/extensions?reset=1
    PHP  21. Civi\\Payment\\System->getByProcessor() civicrm/CRM/Core/Payment.php:100, referer: https://x.org/civicrm/admin/extensions?reset=1

**Comment by eileenmcnaughton** [comment]
Hmm - that enable / disable error is coming from a block I think - so maybe that is part of the reason. Re the settings form - try rebuilding the menu  - go to the url civicrm/menu/rebuild

**Comment by kenwest** [comment]
Eileen, rebuilding the menus did the trick. Thanks!

**Comment by mfuggle** [comment]
I have a similar error and rebuilding the menus does not correct the issue for me
