### ISSUE TITLE
Recurring contributions should be cancelled if they fail with an expired cc date

### ISSUE THREAD

**Issue by eileenmcnaughton** [ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor#36]

**Comment by kenwest** [comment]
Not sure about this. If a CC expires, we call the donor, and usually they can give us a new expiry date.

We can then update the expiry date in eWAY's Token Customer facility.

**Comment by eileenmcnaughton** [comment]
You could probably re-enable the recurring profile if you do that. Cust is concerned about repeated billing on expired cards. Note also that they are using the payment_token extension to query tokens so they have a view of expiry dates & presumably try to contact them before they expire
