### ISSUE TITLE
Move out of Beta?

### ISSUE THREAD

**Issue by mc0e** [ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor#45]
This extension has seen a few years of production use, but is still listed as having `Beta` status at https://civicrm.org/extensions/eway-recurring-payment-processor :

Should there be a `Stable` release now?  If not, maybe a roadmap of what's needed to get there?

Am I right in thinking that this beta status is why this module is not installable from within CiviCRM?  

Looks like the release date and version shown in the [extensions directory](https://civicrm.org/extensions) is also old, so maybe this is just a case of updating the info there?

**Comment by eileenmcnaughton** [comment]
New release done
