### ISSUE TITLE
Install fails - DB Error: Syntax error

### ISSUE THREAD

**Issue by mfuggle** [ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor#51]
When I try to install I get the following backtrace:

`backTrace

#0 /var/www/html/sites/all/modules/civicrm/CRM/Core/Error.php(182): CRM_Core_Error::backtrace()
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /var/www/html/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /var/www/html/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: unknown error", -1, 16, (Array:2), "\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...")
#4 /var/www/html/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-1, 16, (Array:2), "\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...")
#5 /var/www/html/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -1, NULL, NULL, "\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...", "DB_Error", TRUE)
#6 /var/www/html/sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-1, NULL, NULL, NULL, "1419 ** You do not have the SUPER privilege and binary logging is enabled (yo...")
#7 /var/www/html/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /var/www/html/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...")
#9 /var/www/html/sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...")
#10 /var/www/html/sites/all/modules/civicrm/packages/DB/DataObject.php(1634): DB_DataObject->_query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...")
#11 /var/www/html/sites/all/modules/civicrm/CRM/Core/DAO.php(321): DB_DataObject->query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...")
#12 /var/www/html/sites/all/modules/civicrm/CRM/Core/DAO.php(1180): CRM_Core_DAO->query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...", TRUE)
#13 /var/www/html/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php(3296): CRM_Core_DAO::executeQuery("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255) CHARACTER ...")
#14 /var/www/html/sites/all/modules/civicrm/CRM/Core/DAO.php(1868): CRM_Contact_BAO_Contact::triggerInfo((Array:5), NULL)
#15 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(400): CRM_Core_DAO::triggerRebuild()
#16 /var/www/html/sites/all/modules/civicrm/CRM/Extension/Manager.php(246): CRM_Core_Invoke::rebuildMenuAndCaches(TRUE)
#17 /var/www/html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(195): CRM_Extension_Manager->install((Array:1))
#18 /var/www/html/sites/all/modules/civicrm/CRM/Core/Form.php(345): CRM_Admin_Form_Extensions->postProcess()
#19 /var/www/html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(164): CRM_Core_Form->mainProcess()
#20 /var/www/html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#21 /var/www/html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#22 /var/www/html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#23 /var/www/html/sites/all/modules/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("next")
#24 /var/www/html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(395): CRM_Core_Controller->run()
#25 /var/www/html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(174): CRM_Core_Page_Basic->edit(1, NULL)
#26 /var/www/html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(125): CRM_Core_Page_Basic->run()
#27 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#28 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
#29 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#30 /var/www/html/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
#31 [internal function](): civicrm_invoke("admin", "extensions")
#32 /var/www/html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#33 /var/www/html/index.php(21): menu_execute_active_handler()
#34 {main}

Sorry but we are not able to provide this at the moment.
DB Error: unknown error

Return to home page.
`
Regards
Martin Fuggle

**Comment by eileenmcnaughton** [comment]
That error is unrelated to the extension. The install triggered CiviCRM to try to re-install it's triggers & you have not given your mysql user the SUPER permission it needs to do this. The simplest fix is to adjust your mysql user's permissions

**Comment by mfuggle** [comment]
Thanks Eileen - I have been in some trouble since an error in upgrading
from 4.6.14 to 4.6.16. The 4.6.15 upgrade went through OK. At the moment I
can no longer save any tranaction that takes place in a frame. Is that
likely to be the same MySQL issue?


Martin Fuggle

kew: (03) 9817 1401
deans marsh: (03) 5236 3306
mobile: 0408 265 586 e:  martin@fuggle.com.au
w: www.fuggle.com.au
mfuggle

**Comment by eileenmcnaughton** [comment]
... maybe... but try fixing it  & then see

**Comment by mfuggle** [comment]
There were two log files which had a crash status. All of the issues I was experiencing were resolved once the tables were repaired. It was a little odd since the particular tables did not show as crashed when viewed using phpmyadmin even though they showed as crashed in a backtrace. I am using an AWS RDS instance to provide mysql and it is not possible to allocate SUPER privilege to the database user in AWS.

**Comment by eileenmcnaughton** [comment]
well good that it's all sorted now!
