### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by Upperholme** [ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor#55]
Hi. Should this extension be used instead of the eWay processor that ships with Civi, or is it an addition specifically to deal with recurring payments (as the name might suggest)? I'v a client looking at which payment processor they should adopt, and eWay looks an attractive option but I'm not clear on the Civi integration.
Thanks for any response.

**Comment by eileenmcnaughton** [comment]
Yes, use this. I think there is a ticket to remove the core one. This is in use lots of places...
