### ISSUE TITLE
Remove this extension from CiviCRM in-app installation?

### ISSUE THREAD

**Issue by twomice** [ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor#59]
Hi @ChrisChinchilla Long time no see.

Judging from the issue queue and commit log on this repo, I'm guessing maybe it's no longer actively maintained. In that case, I'm inclined to remove it from the list of applications that are available for one-click installation within CiviCRM's "Manage Extensions" screen.

Please let me know if you have thoughts on the matter. In case there's no response, I'll go ahead and make this change after 14 days.

Thanks,
Allen Shaw
CiviCRM Extensions Working Group Lead

**Comment by eileenmcnaughton** [comment]
As far as I know this is still the most used eway plugin

**Comment by eileenmcnaughton** [comment]
@petednz

**Comment by petednz** [comment]
probably worth getting Justin to add his 'state of play' comments here - @eileenmcnaughton if one of us remembers it could come up on our call with him this arvo - i will be in car so may be mostly listening

**Comment by twomice** [comment]
After further discussion, it looks like this extension is getting more attention than I thought. I'm closing this as a "won't fix" i.e., not going to remove it from in-app installation at this point.

**Comment by jusfreeman** [comment]
FYI. This discussion was used as evidence that the extension should **remain listed in the extension directory and in-app installation** - see https://lab.civicrm.org/extensions/extension-review-requests/issues/11

I was not aware of this discussion till now, otherwise, I would have said something.

Now I am saying something.

**Comment by petednz** [comment]
I am fine with it being delisted

**Comment by ChrisChinchilla** [comment]
Happy for someone to take this over. I moved on from Drupal, CiviCRM and that world ages ago, sorry!

**Comment by twomice** [comment]
Cross-post from above-mentioned https://lab.civicrm.org/extensions/extension-review-requests/issues/11:

> I've edited the extension directory node to:
> 
> > Reviewed and ready for automated distribution?:  Closed
> 

Thanks @ChrisChinchilla for confirming the status of this extension, and for contributing it in the first place (I believe lots of people have benefited for a long time from its availability).

**Comment by jusfreeman** [comment]
@ChrisChinchilla thanks mate, appreciated
